export type LogCategory = '온보딩' | '레벨0' | '레벨1' | '레벨3' | '소프트스킬' | '코치훈련'

export interface Log {
  slug: string
  title: string
  description: string
  href: string
  date: string        // YYYY-MM-DD — 페이지 최초 커밋 날짜
  category: LogCategory
}

// 최신 항목을 맨 위에 추가하세요.
const logs: Log[] = [
  {
    slug: 'fe-accessibility-report',
    title: 'FE 접근성 리포트: 자기 서비스를 진단하는 6기·7기 반복 실험',
    description: '성능 리포트 구조를 접근성으로 확장. 6기 리포트를 7기 디스커션에 누적 자산으로 명시한 반복 실험.',
    href: '/education-experiment/logs/fe-accessibility-report',
    date: '2026-04-07',
    category: '레벨3',
  },
  {
    slug: 'fe-ssr-discussion',
    title: 'FE SSR 학습: 토론과 OX퀴즈로 "서버와 클라이언트의 평행세계" 체험하기',
    description: 'JS 평행세계 토론과 OX퀴즈 해설지를 결합해, SSR이라는 추상 개념을 자기 코드 검증으로 체화하는 2단 구조.',
    href: '/education-experiment/logs/fe-ssr-discussion',
    date: '2026-04-07',
    category: '레벨3',
  },
  {
    slug: 'fe-rendering-strategy-workshop',
    title: '렌더링 전략 워크숍: 팀×팀 피드백으로 기술 결정 단단히 만들기',
    description: '"CSR이냐 SSR이냐"를 페이지 단위 논증으로 강제하고, 팀 간 피드백·개정 단계로 결정의 단단함을 키운 워크숍.',
    href: '/education-experiment/logs/fe-rendering-strategy-workshop',
    date: '2026-04-07',
    category: '레벨3',
  },
  {
    slug: 'fe-react-typescript-convention',
    title: 'FE React & TypeScript 컨벤션 워크숍: 5기와 7기 사이의 2년 변화',
    description: '같은 템플릿을 2년 간격으로 운영하며, "사용한다"에서 "왜 사용하는가"로 학습 초점이 이동한 비교 실험.',
    href: '/education-experiment/logs/fe-react-typescript-convention',
    date: '2026-04-07',
    category: '레벨1',
  },
  {
    slug: 'layout-component-workshop',
    title: '유연하게 재사용 가능한 레이아웃 컴포넌트 워크숍',
    description: '"재사용성"이라는 추상어 대신 "긴 라벨", "세로형" 같은 구체적 시나리오로 사용자 입장을 의인화한 컴포넌트 설계 훈련.',
    href: '/education-experiment/logs/layout-component-workshop',
    date: '2026-04-07',
    category: '레벨3',
  },
  {
    slug: 'level3-team-project-retrospective-series',
    title: '레벨3 팀 프로젝트 회고 3부작: 중간 → 최종 → 사용자 유치',
    description: '같은 팀 프로젝트를 시점별로 다른 형식(점수화/3층위/외부 시야)의 회고로 설계해 회고 피로감을 줄인 기록.',
    href: '/education-experiment/logs/level3-team-project-retrospective-series',
    date: '2026-04-07',
    category: '소프트스킬',
  },
  {
    slug: 'ux-research-training',
    title: 'UX 리서치 3단계 훈련: 글쓰기에서 UT 실전까지',
    description: '페어 글쓰기 → JTBD 인터뷰 설계 → UT 실전이라는 3단계 점진적 스캐폴딩으로 개발자의 UX 리서치 역량을 훈련한 기록.',
    href: '/education-experiment/logs/ux-research-training',
    date: '2026-03-27',
    category: '레벨3',
  },
  {
    slug: 'demo-day-retrospective',
    title: '데모데이 회고의 점진적 설계: 자유 형식에서 메타인지까지',
    description: '5회 연속 데모데이 회고를 매회 다른 형식으로 설계하여 성찰 깊이를 점진적으로 끌어올린 실험.',
    href: '/education-experiment/logs/demo-day-retrospective',
    date: '2026-03-27',
    category: '소프트스킬',
  },
  {
    slug: 'fe-level2-16steps',
    title: 'FE 레벨2 16단계 학습 체계: 점진적 깊이로 리액트를 체화하기',
    description: '적게 읽기, 거꾸로 만들기, 관점 전환 — 세 가지 제약으로 설계한 FE 레벨2 전체 16단계 학습 체계.',
    href: '/education-experiment/logs/fe-level2-16steps',
    date: '2026-03-27',
    category: '레벨1',
  },
  {
    slug: 'async-quiz-explanation',
    title: '비동기 퀴즈 해설지 만들기: 설명하며 배우는 3개 기수 반복 실험',
    description: '같은 4개의 비동기 퀴즈를 5기/6기/7기에 반복하며, 해설지 작성을 통해 설명 능력의 변화를 관찰한 실험.',
    href: '/education-experiment/logs/async-quiz-explanation',
    date: '2026-03-27',
    category: '레벨1',
  },
  {
    slug: 'feedback-refactoring',
    title: '피드백 리팩터링: 피드백을 코드처럼 진단하고 개선하는 훈련',
    description: '5가지 진단 기준으로 기존 피드백을 진단하고, 수동 리팩터링과 GPTs 활용을 비교하며 피드백 품질을 높이는 훈련.',
    href: '/education-experiment/logs/feedback-refactoring',
    date: '2026-03-27',
    category: '소프트스킬',
  },
  {
    slug: 'growth-graph',
    title: '나의 성장 그래프: 시각화와 감정 키워드로 레벨을 회고하기',
    description: 'A3 모눈종이에 기술/소프트스킬 성장 곡선을 그리고 감정 키워드를 붙여 레벨을 회고하는 시각적 회고 활동.',
    href: '/education-experiment/logs/growth-graph',
    date: '2026-03-27',
    category: '소프트스킬',
  },
  {
    slug: 'team-building-ground-rules',
    title: '나 사용설명서에서 팀 그라운드 룰까지: 팀 빌딩 미션 (6기)',
    description: '개인 사용설명서로 자기 이해를 먼저 하고, 이를 기반으로 팀 그라운드 룰을 협상하는 2단계 팀 빌딩 설계.',
    href: '/education-experiment/logs/team-building-ground-rules',
    date: '2026-03-27',
    category: '소프트스킬',
  },
  {
    slug: 'finding-tech-strengths',
    title: '나만의 기술적 강점 찾기: 정체성 선언 기반 딥다이브 학습 (7기 FE)',
    description: '"나는 __에 강점이 있는 개발자입니다" 정체성 선언으로 48명의 크루가 각자의 기술 영역을 깊이 탐구한 실험.',
    href: '/education-experiment/logs/finding-tech-strengths',
    date: '2026-03-27',
    category: '소프트스킬',
  },
  {
    slug: 'reinventing-the-wheel',
    title: '바퀴의 재발명 사전 에세이: 3개 기수가 탐구한 재구현의 교육적 가치',
    description: '안드로이드 레벨4 "바퀴의 재발명" 강의 전 사전 에세이 과제. 5기·6기·7기 크루의 사고 깊이 변화를 추적한 기록.',
    href: '/education-experiment/logs/reinventing-the-wheel',
    date: '2026-03-27',
    category: '레벨1',
  },
  {
    slug: 'fe-performance-report',
    title: 'FE 성능 리포트: 자기 서비스를 진단하는 3단계 프레임워크의 진화',
    description: '자기 팀 서비스를 대상으로 성능을 측정하고 개선하는 3단계 프레임워크. 5기·6기·7기에 걸친 진화 과정.',
    href: '/education-experiment/logs/fe-performance-report',
    date: '2026-03-27',
    category: '레벨3',
  },
  {
    slug: 'ux-lecture-level3',
    title: '레벨3 UX 특강: 사용자 관점으로 서비스 다듬기 (6기)',
    description: 'UX Writing, JTBD 인터뷰 설계, UT 인터뷰 3회 시리즈로 개발자가 사용자 관점을 체험하고 서비스를 개선하는 활동.',
    href: '/education-experiment/logs/ux-lecture-level3',
    date: '2026-03-27',
    category: '레벨3',
  },
  {
    slug: 'web-backend-level1-elective-missions',
    title: '웹백엔드 레벨1 선택미션',
    description: '기술·문제정의·사고 확장 3가지 유형의 선택미션으로 자기주도 학습 환경을 설계한 기록.',
    href: '/education-experiment/logs/web-backend-level1-elective-missions',
    date: '2026-03-24',
    category: '레벨1',
  },
  {
    slug: 'expedition-tech-salon',
    title: '원정대 테크살롱: 공유회로 전이 설계하기',
    description: '원정대가 쌓은 지식을 다른 크루에게 실제로 전이시키는 테크살롱 공유회 설계와 운영 기록.',
    href: '/education-experiment/logs/expedition-tech-salon',
    date: '2026-03-24',
    category: '레벨1',
  },
  {
    slug: 'pair-programming-manifesto',
    title: '짝 프로그래밍 선언문',
    description: '첫 미션 후 KPT 회고로 크루가 직접 만든 10가지 협업 원칙. 외부 가이드라인이 아닌 자신들의 언어로 쓴 선언문.',
    href: '/education-experiment/logs/pair-programming-manifesto',
    date: '2026-03-17',
    category: '소프트스킬',
  },
  {
    slug: 'soft-skill-one-step-study',
    title: '한 발짝 스터디',
    description: '크루 스스로 소프트 스킬 목표를 설정하고 매주 팀 스터디로 실험하는 성장 사이클.',
    href: '/education-experiment/logs/soft-skill-one-step-study',
    date: '2026-03-17',
    category: '소프트스킬',
  },
  {
    slug: 'codelab-lotto-domain-ui',
    title: '코드랩으로 관심사 분리 체험하기',
    description: 'POE 사이클로 "도메인과 UI를 왜 분리해야 하는가"를 크루 스스로 발견하게 하는 수업 설계.',
    href: '/education-experiment/logs/codelab-lotto-domain-ui',
    date: '2026-03-17',
    category: '레벨1',
  },
  {
    slug: 'drama-retrospective',
    title: '연극 회고: 취약함 공유로 심리적 안전감 만들기',
    description: '연극 직후 강점과 취약함을 포스트잇으로 공유하며 팀 신뢰의 토대를 만드는 90분 회고 활동.',
    href: '/education-experiment/logs/drama-retrospective',
    date: '2026-03-17',
    category: '온보딩',
  },
  {
    slug: 'drama-onboarding',
    title: '온보딩 연극 미션',
    description: '연극으로 시작하는 온보딩. 심리적 안전감 형성과 팀 정체성을 위한 첫 번째 장치.',
    href: '/education-experiment/logs/drama-onboarding',
    date: '2026-03-17',
    category: '온보딩',
  },
  {
    slug: 'android-level0',
    title: '레벨0: 자기주도 학습 설계 (안드로이드 8기)',
    description: '입학 전 4주, 계획-실행-회고 구조로 자기주도 학습 리듬을 만드는 실험. 19명 전원 완주.',
    href: '/education-experiment/logs/android-level0',
    date: '2026-03-10',
    category: '레벨0',
  },
  {
    slug: 'senior-code-review',
    title: '선배 코드로 눈 키우기',
    description: '선배 PR의 AS-IS를 먼저 판단하고 TO-BE와 비교하여 "못 보던 것"을 발견하는 활동.',
    href: '/education-experiment/logs/senior-code-review',
    date: '2026-03-10',
    category: '레벨1',
  },
  {
    slug: 'expedition',
    title: '원정대: 송곳 같은 강점 만들기',
    description: '동료와 함께 탐험하며 각자의 전문 영역을 만드는 활동.',
    href: '/education-experiment/logs/expedition',
    date: '2026-03-10',
    category: '레벨1',
  },
  {
    slug: 'standardized-crew-coaching',
    title: '표준화 크루를 활용한 코칭 훈련',
    description: 'GPTs로 구현한 가상 크루와 코칭을 연습하는 훈련 환경.',
    href: '/education-experiment/logs/standardized-crew-coaching',
    date: '2026-03-10',
    category: '코치훈련',
  },
  {
    slug: 'mission-design',
    title: 'Gemini Canvas 웹앱 다작하기',
    description: 'AI와 협업하는 방식을 익히기 위한 1주 4앱 미션 설계기.',
    href: '/education-experiment/logs/mission-design',
    date: '2026-03-03',
    category: '레벨1',
  },
]

export default logs
