export interface Update {
  date: string
  title: string
  description: string
  href: string
  status: 'completed' | 'active' | 'upcoming'
}

// 최신 항목을 맨 위에 추가하세요.
const updates: Update[] = [
  {
    date: '2026년 연구',
    title: '크루 성장 여정: 레벨 0→5를 한눈에',
    description:
      '작은 행성이가 낯선 별에 도착해 빛나는 개발자로 자라기까지, 레벨 0부터 5까지의 성장 곡선을 캐릭터와 함께 한 화면에 담았습니다. 커리큘럼이 “무엇을 언제”라면, 이 페이지는 “크루가 어떻게 자라는가”를 이야기로 보여줍니다.',
    href: '/education/journey',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '우테코 현장: 1차 자료·근거 층을 신설',
    description:
      '테코톡·테코블·데모데이·저장소 분석처럼 우테코가 실제로 만들고 말하고 남긴 1차 자료를 “우테코 현장”이라는 이름으로 사이드바에 노출했습니다. 가이드(이해하기·적용하기)가 “이렇게 하세요”라는 결론이라면, 이곳은 그 결론이 나온 “실제로 이렇게 했다”는 현장입니다. 흩어져 있던 콘텐츠 아카이브와 저장소 분석을 하나의 입구로 모으고, 어떤 독자가 언제 보면 좋은지 안내를 더했습니다.',
    href: '/education/conversations',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '우테코 홈페이지를 공식문서로 통합',
    description:
      '따로 운영하던 woowacourse.io(소개·교육과정·지원·FAQ·문의)를 공식문서 안으로 옮겼습니다. "지원" 탭을 새로 두어 모집 일정과 문의를 한곳에 모았고, 모집 정보는 데이터 파일로 관리해 다음 기수엔 한 파일만 고치면 됩니다. 우테코 소개는 교육 탭 상단으로 편입했습니다.',
    href: '/apply',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '크루의 목소리: 데이터 빈도 맵 + 아카이브 신설',
    description:
      '우테코를 거쳐 간 크루들이 남긴 메시지를 추천사 카드가 아니라 "무엇이 가장 많이 나왔나"라는 데이터로 보여준다. 랜딩에서는 "크루는 어디로 갔나(결과)" 다음에, 메시지에서 반복된 주제를 글자 크기(빈도)로 인코딩한 타이포그래픽 빈도 맵을 두고, 주제를 누르면 대표 문장이 뜬다. 아카이브에는 그 근거가 되는 개별 메시지 전체를 둔다. 현재 빈도·문구는 실제 메시지를 받기 전 예시다.',
    href: '/education/conversations/crew-voices',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '실험 로그: 8기 프론트엔드 미션 3종 PR 분석',
    description:
      '레벨1 프론트엔드 미션 3종의 2026년 PR 137건·리뷰 코멘트를 분석해 실험 로그로 정리했다. 로또(콘솔→웹 관심사 분리), ts러닝(학습법을 학습하는 신설 미션), 영화리뷰(비동기 에러와 상태 기반 설계의 첫 만남). 커리큘럼 페이지에서 올해 핵심 교육 경험과 함께 연결된다.',
    href: '/education/logs/fe-lotto-2026-prs',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '검증된 패턴: 비기술 첫 미션 승격',
    description:
      '연극 온보딩에서 "비-기술 첫 미션으로 역량 불안과 관계 불안을 분리한다"는 설계 원칙을 검증된 패턴으로 승격했다. 기수가 바뀌어도 첫 미션을 연극으로 고정해 온 반복 검증이 근거이며, 연극 온보딩·회고 설계와 연결된다.',
    href: '/education/insights/non-technical-first-mission',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '검증된 도구: AI 협업 미션 신설',
    description:
      '올해 전 트랙 공통으로 진행한 Gemini Canvas 웹앱 미션을 복사해 설계하는 키트를 추가했다. 1주 4개 앱·페어 프롬프트 릴레이·피드백 즉시 개선 데모데이·AI 사용 일지 구조와, 145개 PR에서 반복된 프롬프팅 패턴(구조화 프롬프트·제약 선언·반복 개선)을 담았다. 미션 설계 로그가 근거.',
    href: '/education/tools/ai-collaboration-mission-kit',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '검증된 도구: 연극 온보딩 신설',
    description:
      '입학 첫 주 연극 미션을 복사해 설계하는 키트를 검증된 도구에 추가했다. 역량 불안과 관계 불안을 분리하는 첫 장치로서 운영 구조 템플릿·요구사항의 교육적 의도·MC 제도·8기 28개 주제 카탈로그를 담았고, 회고 설계는 회고 형식 키트로 연결한다. 8기 연극 미션·연극 회고 로그가 근거.',
    href: '/education/tools/drama-onboarding-kit',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '공개 합작 회고 패턴 신설: 우테코 회고 저장소에서 추출',
    description:
      'woowacourse/retrospective 공개 디스커션 4년치(2022~2026)를 분석해, 회고의 "형식"과 직교하는 "진행·공유" 축의 패턴 3가지(한 코멘트 합작 · 공개 아카이브 · 역할 로테이션)를 정리했다. 회고를 함께 써서 공개로 남기면 1회성 성찰이 기수를 넘는 학습 자산이 된다. 기존 회고 설계·형식 키트와 직교 축으로 연결된다.',
    href: '/education/insights/public-retrospective',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '"어떻게 만들어지는가"에 루브릭 설명과 점수의 통계적 읽기 추가',
    description:
      '품질 루브릭(형식·서술)과 승격 루브릭(내용·패턴)이 각각 무엇을 보는지 풀어 쓰고, LLM 점수를 한 번의 진실이 아니라 분포에서 뽑은 표본으로 다루는 통계 원칙을 더했다. 표본은 무작위 잡음만 줄일 뿐 편향은 못 줄이므로 경계값은 사람이 승인한다는 역할 분담을 명시했고, 아직 로그당 1회 채점이라는 한계도 솔직히 표시한다.',
    href: '/education/how-its-made',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '"이 문서는 어떻게 만들어지는가" 신뢰 페이지 신설',
    description:
      '외부 독자가 결과물만 보고 갖는 "이거 그냥 멋진 말 아닌가" 의심에 답하기 위해, 콘텐츠가 실험 로그에서 귀납되고 루브릭 게이트(품질 25점·승격 20점)로 검증되며 계속 수정되는 제작 과정을 시각화했다. 게이트를 누르면 실제 채점 기준이 펼쳐진다.',
    href: '/education/how-its-made',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '시작하기 페이지 신설 + 교육 IA를 두 모드(이해·적용)로 재편',
    description:
      '"이해하기"와 "적용하기" 두 독자 모드를 개요의 두 문과 사이드바 그룹으로 명시화하고, 적용 모드의 입구로 우테코 모델을 5분 안에 잡는 시작하기 페이지를 추가했다.',
    href: '/education/start',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '커리큘럼을 "철학을 10개월로 옮기는 법"으로 재구성',
    description:
      '커리큘럼을 연도별 변천사 보기에서 철학 원리의 배치 레이어로 재정의했다. 누적 학습 모델·레벨 구조와 스캐폴딩·역순 설계 세 원칙이 각각 철학 원리(↑)와 실험 로그 증거(↓)에 연결되고, 연도별 타임라인은 "누적 학습 모델"의 증거로 자리 잡았다. 빌더가 왜→어떻게 배치→실제 증거를 한 줄기로 따라갈 수 있다.',
    href: '/education/curriculum',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '커리큘럼 연도별 변화 타임라인 신설',
    description:
      '2021–2026 커리큘럼의 진화를 "영구 골격 + 누적 추상화" 모델로 정리한 연도별 타임라인을 추가. react-payments 5년 분석을 원본으로 distill했고, 데이터가 얇은 해는 "기록 보강 중"으로 솔직히 표시한다.',
    href: '/education/curriculum',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '교육 철학 핵심 원칙을 실험 로그로 채우다 (자기주도·몰입·협업)',
    description: '비어 있던 자기주도 학습·몰입 기반 성장·함께 성장하는 문화 3개 원칙을 자기 진단·점진적 스캐폴딩·논증 기반 학습 인사이트와 12개 로그·555 PR 정량 데이터에 연결해 정리했다. 철학이 추상적 선언이 아니라 경험에서 귀납됨을 드러낸다.',
    href: '/education/philosophy',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '승격: 회고 설계 (인사이트 + 도구 + 디자인 패턴)',
    description: '4개의 회고 로그(데모데이 5회·레벨3 3부작·연극 회고·성장 그래프)에서 "회고 형식을 매번 전환해 성찰 깊이를 점증시킨다"는 교차 패턴을 추출해 인사이트 1개·도구 1개를 신설하고, 디자인 패턴 카탈로그에 패턴 10을 추가.',
    href: '/education/insights/retrospective-design',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '승격: 미션은 누적 학습 모델이다 (인사이트 + 도구 + 디자인 패턴)',
    description: '페이먼츠 5년 분석 로그를 승격해 인사이트 1개·도구 1개를 신설하고, 디자인 패턴 카탈로그와 커리큘럼 설계 원칙에 정량 증거 마커 섹션을 추가.',
    href: '/education/insights/mission-learning-accumulation',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: 'React 페이먼츠 미션 5년치 PR 555개 데이터 분석',
    description: 'woowacourse/react-payments 저장소 555개 PR(2021–2026)의 본문·리뷰 코멘트 2,360건을 정량 분석해 학습 주제 진화·리뷰어 코칭 패턴·미션 재설계 흔적을 추적했다.',
    href: '/education/logs/react-payments-555prs-analysis',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '포수타 코치 Q&A 5회 누적 패턴 로그',
    description: '2024-2025년 포수타 5회 전사를 묶어, 시간 부족·완벽주의·관계·취업·재미라는 반복 주제와 코치들의 우테코식 가이드 어법을 정리한 메타 로그.',
    href: '/education/logs/posuta-coach-qa-archive',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '크루들과의 포수타 5회 스크립트 아카이브',
    description: '포비 캡틴과 6~7기 크루들의 포수타 5회 전사를 정리하고, 방향 설정에서 학습 태도·관계 맺기로 이동한 질문 흐름을 함께 읽었다.',
    href: '/education/logs/posuta-archive',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '안드로이드 레벨2 미니 프로젝트 수업 계획',
    description: '안드로이드 레벨2 크루 17명을 대상으로 4주 8회차 MVP 빌더 성장을 목표로 설계된 미니 프로젝트 수업 계획서.',
    href: '/education/logs/android-level2-mini-project',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '레벨2 지키미 선택 과목 - 고맙다 피드백 워크숍',
    description: 'Stone & Heen의 Thanks for the Feedback 프레임(3종 피드백, 3트리거, SSCC, 7일 약속)을 레벨2 지키미 선택 과목 90분 워크숍 6활동으로 설계합니다.',
    href: '/education/logs/thanks-feedback-workshop',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 @MVC 미션 (스프링 MVC 프레임워크 직접 구현, Java)',
    description: '스프링 @MVC를 직접 구현하며 379회 포크·400+ PR 누적. Controller 반환 타입 일관성·Handler 추상화·JsonView 응답 형식·점진적 리팩토링이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/java-mvc',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 JDBC 미션 (스프링 JDBC 라이브러리 직접 구현, Java)',
    description: '스프링 JDBC를 직접 구현하며 376회 포크·400+ PR 누적. Connection 캡슐화·Optional 일관성·트랜잭션 전파·예외 체이닝이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/java-jdbc',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바스크립트 영화 리뷰 미션 (DOM 설계, JavaScript)',
    description: 'FE 레벨1 영화 리뷰 미션으로 155회 포크·200+ PR 누적. DOM 설계·상태 관리·컴포넌트 추상화·데이터 모델링이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/javascript-movie-review',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '프론트엔드 성능 베이스캠프 (Memegle 최적화, JavaScript)',
    description: 'Memegle 성능 개선 미션으로 205회 포크·191 PR 누적. 이미지 최적화·번들 최적화·캐싱·코드 스플리팅이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/perf-basecamp',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 HTTP 미션 (톰캣 직접 구현, Java)',
    description: '톰캣을 직접 구현하며 385회 포크·1,100+ PR 누적. 세션 보안·쿠키 파싱·에러 핸들링 일관성이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/java-http',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '리액트 페이먼츠 미션 (UI 컴포넌트 설계, TypeScript)',
    description: '결제 카드 UI를 2단계로 구현하며 207회 포크·496 PR 누적. 커스텀 훅·접근성·TypeScript 타이핑이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/react-payments',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 로또 미션 (구현→리팩토링 2단계, Java)',
    description: '로또 구현 1단계·리팩토링 2단계 구조로 327회 포크·676 PR 누적. 단일 책임·일급 컬렉션이 핵심 리뷰 주제.',
    href: '/education-experiment/repositories/java-lotto',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 체스 미션 (OOP 심화·DB 연동, Java)',
    description: 'OOP 심화와 DB 연동을 주제로 461회 포크·857 PR이 누적된 대표 심화 미션 레포.',
    href: '/education-experiment/repositories/java-chess',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '자바 블랙잭 미션 (다기수 누적, Java)',
    description: 'OOP 설계 원칙과 입력 검증 책임 분리를 핵심 주제로, 549회 포크·1,000+ PR이 누적된 대표 미션 레포.',
    href: '/education-experiment/repositories/java-blackjack',
    status: 'active',
  },
  {
    date: '2026년 연구',
    title: '우아한테크코스 저장소 연구 (신규)',
    description: 'woowacourse org 전체 공개 저장소를 autoresearch 파이프라인으로 분석하기 시작했습니다.',
    href: '/education-experiment/repositories',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '우테코 유튜브 채널 아카이브',
    description: '새로 분리된 우테코 유튜브 채널의 공개 영상 5편을 읽고, 지원·데일리미팅·페어프로그래밍·팀프로젝트·브이로그 흐름으로 다시 엮은 안내 페이지.',
    href: '/education/conversations/uteco-youtube-archive',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '테코톡 아카이브',
    description: '테코톡 재생목록 669편을 서버·프론트엔드·모바일·DB·네트워크 같은 카테고리와 키워드로 다시 묶고, 검색형 탐색 UI로 궁금한 주제부터 바로 찾을 수 있게 구성.',
    href: '/education/conversations/techtalk-archive',
    status: 'active',
  },
  {
    date: '7기·8기',
    title: '코칭 스쿼드 전문성 강화 루프',
    description: '회상, 표준화 크루, 클린 랭귀지, GPT 반복 훈련, 원온원 준비 템플릿으로 이어진 11회차 코치 훈련 흐름을 한 편의 로그로 정리.',
    href: '/education/logs/coaching-squad-training-loop',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '브이로그 아카이브',
    description: '우테코 브이로그 재생목록 28편을 하루, 캠퍼스, 프로젝트, 행사, 운영 키워드로 다시 묶고 검색형 탐색 UI까지 붙여 궁금한 장면부터 바로 찾을 수 있게 구성.',
    href: '/education/conversations/vlog-archive',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '교육 설명회 아카이브',
    description: '우테코 교육설명회 재생목록 23편을 입학 설명회, 코치와 수다 타임, 교육자 관점 강연, 운영 Q&A로 다시 묶어 읽기 쉽게 구성.',
    href: '/education/conversations/education-briefing-archive',
    status: 'active',
  },
  {
    date: '7기',
    title: '논증 기반 학습 설계 인사이트',
    description: '정답을 주지 않고 설명하게 만드는 패턴. 4개 로그에서 레벨1~4에 걸쳐 발견된 교차 패턴을 인사이트로 정리.',
    href: '/education/insights/argumentation-based-learning',
    status: 'active',
  },
  {
    date: '7기',
    title: '렌더링 전략 결정 워크숍 템플릿',
    description: '선언→피드백→개정 3단계로 기술 결정을 논증 훈련으로 만드는 워크숍 운영 템플릿. 7기 FE 레벨4 검증.',
    href: '/education/tools/rendering-strategy-workshop',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '포수타 아카이브 4회차 추가',
    description: '2024년 9월부터 2025년 5월까지의 포수타 녹음 4회를 정리해, 레벨4 우선순위부터 완벽주의, 관계, 개발의 재미까지 반복되는 질문을 다시 읽을 수 있게 구성.',
    href: '/education/conversations/posuta',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '프로젝트 데모데이 아카이브',
    description: '우테코 프로젝트 재생목록 194편을 차수·기수 흐름으로 정리하고, 같은 서비스를 1차·3차·5차 데모로 이어서 볼 수 있게 구성.',
    href: '/education/conversations/demo-day-archive',
    status: 'active',
  },
  {
    date: '아카이브',
    title: '인터뷰 챌린지 아카이브',
    description: '우테코 인터뷰 챌린지 45개 영상을 주제별로 정리하고, “무엇이 궁금하면 어떤 영상을 보면 되는지” 바로 찾을 수 있게 구성.',
    href: '/education/conversations/interview-challenge-archive',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '실험 로그 탐색 구조 개편',
    description: '실험 로그를 레벨·트랙·소프트스킬·코치훈련 기준의 다중 분류로 재구성하고, 사이드바에 레벨별 뎁스를 추가.',
    href: '/education/logs',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '우테코 토크 아카이브 신설: 2026년 8기 브수타 1회차',
    description: '인터뷰, 수다 타임, 테코톡까지 담을 토크형 콘텐츠 아카이브를 열고, 첫 기록으로 브수타 8기 1회차를 정리.',
    href: '/education/conversations/bsuta/2026-8th',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '교육 모델 승격: 3개 교차 패턴',
    description: '연구 사이클로 로그 29개를 측정해 POE 발견 학습·자기 진단 프레임워크·점진적 스캐폴딩을 인사이트와 교육 모델로 승격.',
    href: '/education/insights',
    status: 'active',
  },
  {
    date: '아카이브',
    title: 'FE 레벨3·4 워크숍 6편 아카이브',
    description: '접근성 리포트, SSR 토론, 렌더링 전략, TS 컨벤션, 레이아웃 컴포넌트, 레벨3 회고 3부작 등 GitHub Discussions 기반 6개 실험 로그를 일괄 자산화.',
    href: '/education/logs',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '연구 사이클 워크플로우',
    description: '실험 로그 → 검증된 도구 → 인사이트 → 교육 모델로의 승격 파이프라인을 Mermaid로 시각화.',
    href: '/education/tools/research-cycle-workflow',
    status: 'active',
  },
  {
    date: '2024년 6기',
    title: '레벨3 UX 특강: 사용자 관점으로 서비스 다듬기',
    description: 'UX Writing, JTBD 인터뷰 설계, UT 인터뷰 3회 시리즈로 개발자가 사용자 관점을 체험하고 서비스를 개선하는 활동.',
    href: '/education/logs/ux-lecture-level3',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '웹백엔드 레벨1 선택미션',
    description: '기술·문제정의·사고 확장 3가지 유형의 선택미션으로 자기주도 학습 환경을 설계한 기록.',
    href: '/education/logs/web-backend-level1-elective-missions',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '원정대 테크살롱: 공유회로 전이 설계하기',
    description: '원정대가 쌓은 지식을 다른 크루에게 실제로 전이시키는 테크살롱 공유회 설계와 운영 기록.',
    href: '/education/logs/expedition-tech-salon',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '한 발짝 스터디',
    description: '크루 스스로 소프트 스킬 목표를 설정하고 매주 팀 스터디로 실험하는 성장 사이클.',
    href: '/education/logs/soft-skill-one-step-study',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '온보딩 연극 미션',
    description: '연극으로 시작하는 온보딩. 심리적 안전감 형성과 팀 정체성을 위한 첫 번째 장치.',
    href: '/education/logs/drama-onboarding',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '연극 회고: 취약함 공유로 심리적 안전감 만들기',
    description: '연극 직후 강점과 취약함을 포스트잇으로 공유하며 팀 신뢰의 토대를 만드는 90분 회고 활동.',
    href: '/education/logs/drama-retrospective',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '코드랩으로 관심사 분리 체험하기',
    description: 'POE 사이클로 "도메인과 UI를 왜 분리해야 하는가"를 크루 스스로 발견하게 하는 수업 설계.',
    href: '/education/logs/codelab-lotto-domain-ui',
    status: 'active',
  },
  {
    date: '2026년 8기',
    title: '레벨0: 자기주도 학습 설계 (안드로이드)',
    description: '입학 전 4주, 계획-실행-회고 구조로 크루 스스로 학습 리듬을 만드는 실험. 19명 전원 완주.',
    href: '/education/logs/android-level0',
    status: 'active',
  },
  {
    date: '2025년 8기',
    title: '선배 코드로 눈 키우기',
    description: '선배 PR의 AS-IS를 먼저 판단하고 TO-BE와 비교하여 "못 보던 것"을 발견하는 활동.',
    href: '/education/logs/senior-code-review',
    status: 'active',
  },
  {
    date: '2025년 8기',
    title: '표준화 크루를 활용한 코칭 훈련',
    description: 'GPTs로 구현한 가상 크루와 코칭을 연습하는 훈련 환경.',
    href: '/education/logs/standardized-crew-coaching',
    status: 'active',
  },
  {
    date: '2025년 8기',
    title: '원정대: 송곳 같은 강점 만들기',
    description: '동료와 함께 탐험하며 각자의 전문 영역을 만드는 활동.',
    href: '/education/logs/expedition',
    status: 'active',
  },
  {
    date: '2025년 8기',
    title: 'Gemini Canvas 미션: PR 리뷰 패턴 분석',
    description: '145개 PR 리뷰 대화에서 추출한 8가지 반복 패턴. 프롬프팅 전략부터 피어 리뷰 구조까지.',
    href: '/education/logs/mission-design',
    status: 'completed',
  },
  {
    date: '2025년 8기',
    title: 'Gemini Canvas 웹앱 다작하기 미션 설계',
    description: 'AI와 협업하는 방식을 익히기 위한 1주 4앱 미션 설계기.',
    href: '/education/logs/mission-design',
    status: 'completed',
  },
]

export default updates
